import Link from 'next/link'
import { ArrowRight, Check, Globe2 } from 'lucide-react'
import { services } from '@/lib/services'
import { englishServices } from '@/lib/services-en'
import type { Locale } from '@/lib/i18n'

type GuideSection = { serviceKey: string; title: string; paragraphs: string[]; points?: string[]; anchor: string }

const categoryLabels = {
  tr: ['Web ve Yazılım', 'Özel Yazılım', 'Müşteri Yönetimi', 'Kurumsal Yönetim', 'Otomasyon', 'Bulut Ürünleri', 'Dijital Platformlar', 'Dijital Ticaret', 'Mobil Ürünler', 'Sistem Entegrasyonu', 'Veri ve Raporlama', 'Yapay Zeka', 'Kurumsal Web', 'Dijital Büyüme', 'Modernizasyon'],
  en: ['Web & Software', 'Custom Software', 'Customer Management', 'Enterprise Management', 'Automation', 'Cloud Products', 'Digital Platforms', 'Digital Commerce', 'Mobile Products', 'System Integration', 'Data & Reporting', 'Artificial Intelligence', 'Corporate Web', 'Digital Growth', 'Modernization'],
} as const

const editorialHighlights = {
  tr: {
    'web-yazilim-gelistirme': 'Web sitesi değil, işletmenizin çalışan dijital altyapısı.',
    'ozel-yazilim-gelistirme': 'Teknolojiyi süreçlerinize uyduruyoruz; süreçlerinizi hazır yazılıma uydurmuyoruz.',
    'crm-yazilim-cozumleri': 'Her müşterinin geçmişi, her satış fırsatının durumu tek ekranda.',
    'erp-yazilim-cozumleri': 'Dağınık operasyonları tek bir dijital sistem altında birleştirin.',
  },
  en: {
    'web-yazilim-gelistirme': 'Not another website, but a digital operating layer for your business.',
    'ozel-yazilim-gelistirme': 'We adapt technology to your processes—not your processes to generic software.',
    'crm-yazilim-cozumleri': 'Every customer history and every sales opportunity, visible in one place.',
    'erp-yazilim-cozumleri': 'Bring fragmented operations together under one digital system.',
  },
} as const

const trSections: GuideSection[] = [
  { serviceKey: 'web-yazilim-gelistirme', title: 'Web Yazılım Geliştirme', anchor: 'Web Yazılım Geliştirme hizmetimizi inceleyin', paragraphs: ['Web yazılım; tarayıcı üzerinden çalışan, kullanıcıların yalnızca bilgi okumak yerine veri girdiği, görev tamamladığı ve iş süreçlerini yönettiği uygulamaları ifade eder. Klasik bir web sitesi kurumsal anlatım ve iletişim için hazırlanırken web uygulaması; kullanıcı hesabı, veritabanı, rol ve yetki sistemi, iş kuralları ve entegrasyonlarla aktif bir çalışma ortamı oluşturur. Yönetim panelleri, müşteri portalları, rezervasyon ve operasyon uygulamaları bu yapının yaygın örnekleridir.', 'İşletmeye özel web tabanlı sistemlerde süreçleri, kullanıcı rollerini, raporlama ihtiyaçlarını ve mevcut veri kaynaklarını birlikte analiz ederiz. Responsive arayüzler masaüstü, tablet ve telefonda tutarlı çalışırken dashboard ekranları doğru kişiye doğru veriyi gösterir. API bağlantıları ve veritabanı entegrasyonları bilgi akışını merkezileştirir. Performans, erişim kontrolü, doğrulama, izlenebilirlik ve ölçeklenebilir mimari ise uygulamanın kullanıcı ve işlem hacmi büyüdüğünde güvenilir kalmasını sağlar.'] },
  { serviceKey: 'ozel-yazilim-gelistirme', title: 'İşletmenize Özel Yazılım Geliştirme', anchor: 'Özel yazılım geliştirme yaklaşımımızı inceleyin', paragraphs: ['Hazır paket yazılımlar hızlı başlangıç ve standart süreçler için uygun olabilir; ancak işletme kendine özgü onaylar, fiyatlandırma kuralları, departmanlar arası akışlar veya entegrasyonlar kullanıyorsa ekipler çoğu zaman yazılıma uyum sağlamak zorunda kalır. Özel yazılım geliştirme, çözümü mevcut iş akışına göre şekillendirir. İhtiyaç analiziyle roller, veri, istisnalar ve başarı ölçütleri belirlenir; ardından yalnız gerekli modüller planlanır.', 'KOBİ’ler dağınık tabloları ve manuel takibi merkezi bir operasyon sistemine taşıyabilir. Orta ölçekli işletmeler satış, sipariş, servis ve raporlamayı birleştirebilir; kurumsal yapılar ise çok departmanlı süreçleri ayrıntılı yetkilendirme ve denetim kayıtlarıyla yönetebilir. Modüler ve ölçeklenebilir mimari yeni süreçlerin eklenmesini kolaylaştırır. Bakım, güvenlik güncellemeleri ve ölçülebilir geliştirme planı sayesinde yazılım tek seferlik proje değil, işletmeyle gelişen sürdürülebilir bir ürün olur.'] },
  { serviceKey: 'crm-yazilim-cozumleri', title: 'CRM Yazılım Çözümleri ile Müşteri Süreçlerinizi Yönetin', anchor: 'CRM Yazılım Çözümlerimizi keşfedin', paragraphs: ['CRM yazılımı; müşteri ve şirket kayıtlarını, potansiyel müşterileri, lead kaynaklarını, görüşme geçmişini ve satış pipeline’ını tek merkezde toplar. Satış ekibi fırsatların hangi aşamada olduğunu, bir sonraki görevi, teklif durumunu ve hatırlatmaları görebilir. Segmentasyon, dashboard ve raporlama ekranları yöneticilerin ekip performansını, dönüşüm oranlarını ve kaybedilen fırsat nedenlerini takip etmesine yardımcı olur.', 'Hazır bir CRM sistemi yaygın satış modellerini hızlıca karşılayabilir. Şirkete özel CRM geliştirme ise farklı teklif onayları, bayi yapısı, özel müşteri sınıfları, satış sonrası süreçler ve kurumun kullandığı diğer sistemlerle uyum gerektiğinde avantaj sağlar. E-posta ve API entegrasyonları iletişim geçmişini zenginleştirir; otomasyonlar görev, bildirim ve takip adımlarını standartlaştırır. Amaç daha fazla alan üretmek değil, ekiplerin güncel ve güvenilir müşteri verisiyle tutarlı çalışmasını sağlamaktır.'] },
  { serviceKey: 'erp-yazilim-cozumleri', title: 'ERP Yazılım Çözümleri ile İşletmenizi Tek Merkezden Yönetin', anchor: 'ERP çözümlerimiz hakkında detaylı bilgi alın', paragraphs: ['ERP yazılımı; satış, satın alma, stok, depo, sipariş, cari, finans, personel, üretim ve operasyon verilerini ortak bir sistemde ilişkilendirir. Departmanlar aynı kaynağı kullandığında tekrar veri girişi azalır, stok ve sipariş hareketleri izlenebilir, yönetim dashboard’ları güncel göstergeler sunar. Özel ERP geliştirme, standart bir paketin karşılamadığı iş kurallarını, saha akışlarını ve mevcut muhasebe veya üretim sistemlerini kontrollü biçimde bir araya getirir.', 'CRM müşteri ilişkileri ve satış fırsatlarına odaklanırken ERP işletmenin kaynak ve operasyon akışını daha geniş kapsamda yönetir. İki sistem birbirinin alternatifi olmak zorunda değildir; doğru entegrasyonla satış fırsatı siparişe, sipariş stok ve finans hareketlerine dönüşebilir. Böylece ekipler kopuk kayıtlar yerine uçtan uca izlenebilir bir süreç üzerinden çalışır.'] },
  { serviceKey: 'is-surecleri-otomasyonu', title: 'İş Süreçleri Otomasyonu ve Operasyon Yönetimi', anchor: 'İş süreçleri otomasyonu seçeneklerini görün', paragraphs: ['Tekrar eden görev oluşturma, teklif hazırlama, çok aşamalı onay, bildirim, belge üretme, raporlama ve sistemler arası veri aktarımı yazılımla kontrollü biçimde otomatikleştirilebilir. Personel, müşteri ve sipariş iş akışlarında hangi adımın kim tarafından, hangi koşulla tamamlanacağı açıkça tanımlanır.', 'Otomasyonun amacı insan kararını tamamen kaldırmak değil, gereksiz tekrarları azaltıp kritik kararları görünür hale getirmektir. Standart iş akışları operasyon maliyetini ve hata oranını düşürür; zaman damgaları, sorumlular ve denetim kayıtları izlenebilirliği artırır. İstisnalar ayrıca yönetildiğinde ekipler rutin takip yerine müşteri ve iş değeri üreten çalışmalara odaklanabilir.'] },
  { serviceKey: 'saas-yazilim-gelistirme', title: 'SaaS Yazılım ve Bulut Tabanlı Platform Geliştirme', anchor: 'SaaS geliştirme hizmetimizin kapsamını inceleyin', paragraphs: ['SaaS, kullanıcıların yazılıma internet üzerinden abonelik veya paket modeliyle eriştiği ürün yaklaşımıdır. Multi-tenant mimari farklı müşterilerin verisini güvenli biçimde ayırırken ortak altyapının yönetilebilir kalmasını sağlar. Üyelik, paket, kullanım limiti, ödeme entegrasyonu, rol ve yetki, dashboard ve bildirimler ürün modelinin temel parçalarıdır.', 'Yeni bir dijital ürün geliştiren girişimler pazarı ölçülebilir bir MVP ile test edebilir; mevcut şirketler kendi uzmanlıklarını müşterilerine sunulan bir platforma dönüştürebilir. Bulut mimarisi, API tasarımı, izleme ve ölçeklenebilir veri modeli başlangıçtan planlandığında ürün yeni kullanıcılar ve özelliklerle daha güvenli büyür.'] },
  { serviceKey: 'b2b-b2c-platform-gelistirme', title: 'B2B ve B2C Dijital Platform Çözümleri', anchor: 'B2B ve B2C platform çözümlerini keşfedin', paragraphs: ['B2B platformlar bayi veya kurumsal müşterilere özel fiyat, teklif, cari, stok, sipariş ve yetkilendirme deneyimleri sunar. B2C platformlarda ise son kullanıcı üyeliği, ürün veya hizmet satın alma, ödeme, kampanya, müşteri hesabı ve sipariş takibi öne çıkar.', 'B2B’de karar ve fiyatlandırma kuralları daha karmaşık, kullanıcı rolleri daha ayrıntılı olabilir; B2C’de hızlı ve anlaşılır satın alma deneyimi kritik önem taşır. Her iki modelde de merkezi yönetim paneli, güvenli ödeme, ERP/CRM bağlantıları ve ölçeklenebilir altyapı operasyonla dijital kanalın uyumlu çalışmasını sağlar.'] },
  { serviceKey: 'e-ticaret-yazilimi', title: 'E-Ticaret Yazılımı ve Online Satış Sistemleri', anchor: 'E-ticaret yazılımı yaklaşımımızı inceleyin', paragraphs: ['E-ticaret yazılımı; ürün, kategori, varyant, stok, sepet, ödeme, sipariş, kargo, kampanya, kupon ve müşteri hesabını aynı satış akışında birleştirir. Yönetim paneli günlük operasyonu kolaylaştırırken ERP, CRM ve pazaryeri entegrasyonları farklı kanallardaki bilgilerin tutarlı kalmasına yardımcı olur. Teknik SEO, performans ve mobil uyumluluk hem keşfedilebilirlik hem dönüşüm için birlikte ele alınır.', 'Hazır paketler standart kataloglar ve hızlı başlangıç için maliyet avantajı sağlayabilir. Özel e-ticaret yazılımı; karmaşık fiyatlandırma, B2B kuralları, özel ürün konfigürasyonu veya yoğun entegrasyon gerektiğinde daha fazla esneklik sunar. Doğru seçim bütçeye, satış modeline, büyüme hedeflerine ve operasyonun gerçek karmaşıklığına göre yapılmalıdır.'] },
  { serviceKey: 'mobil-uygulama-gelistirme', title: 'iOS ve Android Mobil Uygulama Geliştirme', anchor: 'Mobil uygulama geliştirme hizmetimizi görün', paragraphs: ['Başarılı mobil uygulama, ekran tasarımından önce ürün stratejisi ve kullanıcı ihtiyacıyla başlar. UI/UX akışları; hesap oluşturma, güvenli oturum, push notification, ödeme, konum servisleri ve günlük kullanım senaryolarına göre tasarlanır. Backend ve API katmanı veriyi güvenli biçimde yönetirken yönetim paneli içerik ve operasyon kontrolü sağlar.', 'Mevcut web yazılımıyla entegrasyon, kullanıcıların farklı kanallarda tutarlı deneyim yaşamasına yardımcı olur. Gerçek cihaz testleri, performans ve hata izleme sonrasında App Store ve Google Play gereksinimleri yönetilir. Yayın sonrası güncelleme planı, işletim sistemi değişiklikleri ve kullanıcı geri bildirimi ürünün sürdürülebilirliğini korur.'] },
  { serviceKey: 'api-sistem-entegrasyonlari', title: 'API ve Sistem Entegrasyonları', anchor: 'API ve sistem entegrasyonu seçeneklerini inceleyin', paragraphs: ['REST API ve güvenli entegrasyon katmanları; ERP, CRM, muhasebe, ödeme kuruluşu, kargo, SMS, e-posta, harita ve diğer üçüncü taraf servisler arasında veri akışı sağlar. Böylece ekiplerin bilgiyi bir sistemden indirip diğerine elle taşıması yerine işlemler belirlenen kurallarla otomatik yürür.', 'Sağlıklı entegrasyon yalnız bağlantı kurmak değildir. Kimlik doğrulama, veri eşleme, hata yönetimi, tekrar deneme, loglama ve senkronizasyon sıklığı açıkça planlanmalıdır. Kontrollü entegrasyon sipariş, stok, müşteri ve finans verisinin tutarlılığını artırırken olası kesintilerin operasyon üzerindeki etkisini sınırlar.'] },
  { serviceKey: 'dashboard-raporlama-sistemleri', title: 'Dashboard ve Yönetim Raporlama Sistemleri', anchor: 'Dashboard ve raporlama çözümlerini keşfedin', paragraphs: ['Dashboard sistemleri satış, operasyon, müşteri ve finans verisini KPI’lar, grafikler, tablolar ve filtrelerle karar verilebilir bilgiye dönüştürür. Gerçek zamanlı veya düzenli güncellenen göstergeler yöneticilerin eğilimleri, hedef sapmalarını ve müdahale gerektiren alanları erken görmesini sağlar.', 'Her role aynı ekranı sunmak yerine yönetici, ekip ve operasyon ihtiyaçlarına göre raporlar tasarlanır. Veri kaynaklarının tanımı, hesaplama kuralları ve tarih aralıkları açık olduğunda raporlama güvenilir bir karar destek sistemine dönüşür; yalnızca görsel bir grafik koleksiyonu olarak kalmaz.'] },
  { serviceKey: 'yapay-zeka-destekli-yazilim', title: 'Yapay Zeka Destekli Yazılım Çözümleri', anchor: 'Yapay zeka destekli yazılım kullanım alanlarını görün', paragraphs: ['Yapay zeka; doküman analizi, veri ve müşteri talebi sınıflandırma, içerik işleme, rapor özetleme, kontrollü chatbot veya asistanlar, görüntü analizi ve yeterli veri olduğunda tahminleme gibi belirli iş problemlerinde yararlı olabilir. Mevcut yazılıma API üzerinden eklenen AI katmanı kullanıcıya öneri sunabilir veya yoğun bilgi içinde doğru içeriği bulmayı kolaylaştırabilir.', 'AI her probleme uygun değildir. Veri kalitesi, hata maliyeti, gizlilik, insan denetimi ve ölçülebilir fayda değerlendirilmeden otomasyon kararı verilmemelidir. Bu nedenle önce iş ihtiyacını ve geleneksel kurallarla çözülebilecek alanları inceler, yapay zekayı yalnız anlamlı bir avantaj sağladığında kontrollü biçimde uygularız.'] },
  { serviceKey: 'web-sitesi-gelistirme', title: 'Kurumsal Web Sitesi Tasarımı ve Geliştirme', anchor: 'Kurumsal web sitesi geliştirme hizmetimizi inceleyin', paragraphs: ['Kurumsal web sitesi markanın kimliğini, uzmanlığını ve teklifini ziyaretçiye açık biçimde aktaran temel dijital kanaldır. Bilgi mimarisi, kullanıcı deneyimi, responsive tasarım ve dönüşüm odaklı CTA’lar ziyaretçinin aradığı içeriğe kolayca ulaşmasını sağlar. İçerik yönetimi, güvenli iletişim formları ve çok dilli yapı ekiplerin farklı pazarlara tutarlı biçimde ulaşmasına yardımcı olur.', 'Hız, Core Web Vitals, erişilebilirlik ve teknik SEO altyapısı tasarım kadar önemlidir. Optimize edilmiş görseller, doğru başlık hiyerarşisi, metadata, analytics ve güvenli yayın süreci sitenin sürdürülebilir performansını destekler. Amaç yalnız estetik bir vitrin değil, ölçülebilir iş hedeflerine hizmet eden güvenilir bir kurumsal deneyimdir.'] },
  { serviceKey: 'seo-dijital-pazarlama', title: 'SEO ve Dijital Pazarlama Çözümleri', anchor: 'SEO ve dijital pazarlama hizmetimizi keşfedin', paragraphs: ['SEO; teknik altyapı, site mimarisi, içerik kalitesi ve kullanıcı deneyiminin birlikte geliştirilmesini gerektirir. Tarama ve indeksleme, internal linking, schema, sitemap, performans ve Search Console verileri teknik görünürlüğün temelini oluşturur. İçerik stratejisi ise kullanıcıların gerçek sorularına özgün ve anlaşılır yanıtlar üretir.', 'Organik görünürlük zaman, tutarlılık ve ölçüm gerektirir; belirli bir sıra garantisi vermek doğru değildir. Dönüşüm takibi, nitelikli trafik ve kullanıcı davranışı birlikte değerlendirildiğinde SEO ve dijital pazarlama yatırımı yalnız ziyaret sayısına değil, iş sonucuna göre iyileştirilebilir.'] },
  { serviceKey: 'yazilim-modernizasyonu', title: 'Mevcut Yazılımların Modernizasyonu', anchor: 'Yazılım modernizasyonu yaklaşımımızı inceleyin', paragraphs: ['Eski bir yazılımı tamamen değiştirmek her zaman gerekli veya güvenli değildir. Teknik analizle modern frontend, yeni backend servisleri, API mimarisi, veritabanı optimizasyonu ve responsive arayüz ihtiyaçları önceliklendirilir. Kritik iş kuralları ve veri korunarak aşamalı geçiş planı hazırlanır.', 'Modernizasyon; performans, güvenlik, entegrasyon yeteneği ve bakım kolaylığını geliştirirken iş sürekliliğini korumalıdır. Otomatik testler, izleme ve kontrollü veri taşıma sayesinde risk azaltılır; yeni modüllerin eklenebileceği daha sürdürülebilir bir teknik temel oluşturulur.'] },
]

const enSections: GuideSection[] = trSections.map((section, index) => ({ serviceKey: section.serviceKey, ...[
  ['Web Software Development','Web software turns business processes into secure browser-based applications rather than static pages. Management panels, customer portals, operational tools and dashboards combine databases, permissions and APIs so users can complete real work from any device. Responsive interfaces, validation, performance and scalable architecture are planned together, allowing the platform to grow without losing reliability.','Explore our web software development service'],
  ['Custom Software Development for Your Business','Packaged products are useful for standard workflows, but custom software fits the organization’s actual roles, approvals, reports and integrations. Discovery identifies needs and exceptions before modular development begins. SMEs can replace spreadsheets, growing businesses can connect departments, and enterprise teams can govern complex operations through permissions, automation and maintainable architecture.','Review our custom software development approach'],
  ['CRM Software Solutions for Connected Customer Operations','A CRM system centralizes customer records, leads, pipeline stages, proposals, interaction history, tasks and reminders. Segmentation, dashboards and reporting help sales teams act consistently. A custom CRM becomes valuable when pricing, approvals, dealer structures or integrations do not fit a generic product, while email and API connections keep information current.','Discover our CRM software solutions'],
  ['ERP Software Solutions for Centralized Operations','ERP connects inventory, purchasing, sales, orders, warehouses, finance, personnel and production through shared data. Management dashboards improve visibility across departments. CRM focuses on customer relationships and opportunities; ERP coordinates wider resources and operations. Integrated together, they can turn a sales opportunity into a traceable order and financial process.','Learn more about our ERP solutions'],
  ['Business Process Automation and Operations Management','Automation can create tasks, route approvals, generate documents, send notifications and transfer data between systems. It reduces repetitive work without removing necessary human judgment. Clear rules, exceptions and audit trails lower operational cost and error rates while making ownership and progress easier to follow.','Explore business process automation'],
  ['SaaS and Cloud Platform Development','SaaS products deliver software through subscriptions or plans. Multi-tenant architecture, user management, billing, roles, usage limits, dashboards, APIs and cloud infrastructure must work as one product system. Startups can validate a focused MVP while established businesses can turn expertise into a scalable digital service.','Review our SaaS development capabilities'],
  ['B2B and B2C Digital Platform Solutions','B2B platforms support dealer pricing, quotations, credit, inventory, orders and detailed permissions. B2C platforms prioritize membership, purchasing, payments, campaigns and order tracking. Although their commercial rules differ, both require secure administration, reliable integrations and an experience designed for their users.','Discover B2B and B2C platform development'],
  ['E-Commerce Software and Online Sales Systems','E-commerce software connects products, variants, stock, basket, payment, orders, shipping, promotions and customer accounts. ERP, CRM and marketplace integrations keep operations aligned. Packaged platforms suit standard and rapid launches; custom commerce is better when pricing, configuration or integration rules are genuinely complex.','Explore our e-commerce development service'],
  ['iOS and Android Mobile App Development','Mobile products begin with strategy and user journeys, then combine UI/UX, accounts, push notifications, payments, location services, APIs and backend systems. Management tools support operations while integration with existing web software keeps data consistent. Device testing, store release and continuous maintenance protect the product after launch.','See our mobile app development service'],
  ['API and System Integrations','REST APIs connect ERP, CRM, accounting, payments, shipping, SMS, email, maps and other third-party services. They replace manual data transfer with controlled synchronization. Authentication, mapping, retries, logs and error handling are essential so a temporary service failure does not become an operational data problem.','Review our API and integration services'],
  ['Dashboard and Management Reporting Systems','Dashboards transform sales, operational, customer and financial data into KPIs, charts, filters and role-specific management views. Clear definitions and reliable sources matter more than decorative graphs. Designed well, reporting highlights trends, exceptions and decisions that require attention.','Discover dashboard and reporting solutions'],
  ['AI-Powered Software Solutions','Practical AI applications include document analysis, classification, support assistants, summarization, content processing and carefully evaluated prediction. AI is not the right solution for every problem; data quality, privacy, error cost and human oversight must be assessed first. We apply it only where it creates measurable value.','Explore responsible AI software applications'],
  ['Corporate Website Design and Development','A corporate website should express brand identity through clear architecture, responsive design and accessible content. Fast loading, Core Web Vitals, technical SEO, secure forms, multilingual publishing, analytics and purposeful calls to action turn it into a dependable business channel rather than a static brochure.','Review our corporate website development service'],
  ['SEO and Digital Marketing Solutions','Technical SEO covers crawlability, architecture, internal links, structured data, sitemaps, performance and Search Console insights. Content strategy answers real audience needs while conversion tracking connects visibility with outcomes. Sustainable organic growth requires evidence and iteration; responsible work never promises a guaranteed ranking.','Explore our SEO and digital marketing service'],
  ['Modernizing Existing Software','Modernization improves legacy systems through a renewed frontend, service-based backend, APIs, database optimization and responsive interfaces. A phased plan protects critical rules, data and continuity. Testing, monitoring and controlled migration reduce risk while creating a more secure, maintainable foundation for future development.','Review our software modernization approach'],
][index].reduce((result, value, valueIndex) => valueIndex === 0 ? { ...result, title: value } : valueIndex === 1 ? { ...result, paragraphs: [value] } : { ...result, anchor: value }, {} as Partial<GuideSection>) })) as GuideSection[]

const processTr = ['İhtiyaç ve İş Analizi','Teknik Planlama','UI/UX Tasarımı','Yazılım Geliştirme','Entegrasyonlar','Test ve Güvenlik Kontrolleri','Canlıya Alma ve Sürekli Geliştirme']
const processEn = ['Needs & Business Analysis','Technical Planning','UI/UX Design','Software Development','Integrations','Testing & Security Review','Launch & Continuous Improvement']

export function ServicesSeoContent({ locale = 'tr' }: { locale?: Locale }) {
  const english = locale === 'en'
  const sections = english ? enSections : trSections
  const source = english ? englishServices : services
  const prefix = english ? '/en/services' : '/tr/hizmetler'
  const processes = english ? processEn : processTr
  const categories = english ? categoryLabels.en : categoryLabels.tr
  const highlights = english ? editorialHighlights.en : editorialHighlights.tr
  const industries = english
    ? ['SMEs', 'Enterprise', 'E-Commerce', 'Manufacturing', 'Logistics', 'Services', 'Foreign Trade', 'Field Operations', 'Startups']
    : ['KOBİ', 'Kurumsal Şirketler', 'E-Ticaret', 'Üretim', 'Lojistik', 'Hizmet', 'Dış Ticaret', 'Saha Operasyonları', 'Girişimler']

  return <section aria-labelledby="services-guide-heading" className="overflow-hidden border-b border-border bg-background">
    <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 md:py-24">
      <header className="max-w-4xl">
        <p className="text-sm font-semibold uppercase tracking-widest text-accent">{english ? 'Digital Transformation & Software Solutions' : 'Dijital Dönüşüm ve Yazılım Çözümleri'}</p>
        <h2 id="services-guide-heading" className="mt-3 text-balance font-display text-3xl font-bold sm:text-4xl">{english ? 'Web, Software and Digital Solutions Built for Your Business' : 'İşletmenize Özel Web, Yazılım ve Dijital Çözümler'}</h2>
        <div className="mt-6 space-y-4 text-lg leading-8 text-muted-foreground"><p>{english ? 'Pars Medya is more than a team that builds corporate websites. We examine business goals, users, data and daily operations before connecting product design, software engineering and measurable digital growth. This integrated approach covers web software, custom development, CRM and ERP platforms, SaaS products, mobile applications, e-commerce and API integrations.' : 'Pars Medya yalnızca kurumsal web sitesi hazırlayan bir ajans değildir. İşletmenin hedeflerini, kullanıcılarını, verisini ve günlük operasyonlarını analiz ederek tasarım, yazılım geliştirme ve ölçülebilir dijital büyüme süreçlerini bütüncül biçimde ele alırız. Web yazılım, özel yazılım geliştirme, CRM ve ERP yazılımı, SaaS, mobil uygulama, e-ticaret ve API entegrasyonu aynı iş hedefi çevresinde planlanır.'}</p><p>{english ? 'We use process automation and responsible AI where they create a clear operational advantage, while performance, security, maintainability and user experience guide every technical decision. SEO and digital marketing help the resulting product reach the right audience and turn attention into measurable action.' : 'İş süreçleri otomasyonu ve yapay zekayı yalnız açık bir operasyonel fayda sağladığı yerde kullanırız. Performans, güvenlik, sürdürülebilir bakım ve kullanıcı deneyimi her teknik kararın parçasıdır. SEO ve dijital pazarlama ise geliştirilen dijital ürünün doğru kitleye ulaşmasını ve görünürlüğün ölçülebilir aksiyona dönüşmesini destekler.'}</p></div>
      </header>

      <div className="mt-16 space-y-8 md:mt-24 md:space-y-12">
        {sections.map((item, index) => {
          const service = source.find((candidate) => english ? 'trSlug' in candidate && candidate.trSlug === item.serviceKey : candidate.slug === item.serviceKey)
          if (!service) return null
          const Icon = service.icon
          const highlight = highlights[item.serviceKey as keyof typeof highlights]
          const featureNames = service.features.slice(0, 6).map((feature) => feature.title)
          const benefits = service.benefits?.slice(0, 4) ?? []
          const number = String(index + 1).padStart(2, '0')

          return <article key={item.serviceKey} className={`relative isolate overflow-hidden rounded-3xl border border-border px-5 py-12 shadow-sm sm:px-8 md:px-12 md:py-20 ${index % 2 === 0 ? 'bg-card' : 'bg-secondary/35'}`}>
            <div aria-hidden="true" className="absolute -right-2 -top-10 -z-10 font-display text-[8rem] font-bold leading-none text-primary/[0.035] sm:right-8 sm:text-[11rem]">{number}</div>
            <div aria-hidden="true" className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-accent via-accent/35 to-transparent" />
            <div className="max-w-4xl">
              <div className="flex items-center gap-3 text-xs font-bold uppercase tracking-[0.18em] text-accent sm:text-sm">
                <span>{number}</span><span className="h-px w-8 bg-accent/50" /><span>{categories[index]}</span>
              </div>
              <div className="mt-6 flex items-start gap-4">
                <span className="hidden rounded-2xl border border-accent/20 bg-accent/10 p-3 text-accent sm:inline-flex"><Icon className="h-6 w-6" aria-hidden="true" /></span>
                <div><h3 className="text-balance font-display text-2xl font-bold sm:text-3xl md:text-4xl">{item.title}</h3><p className="mt-4 max-w-3xl text-pretty text-lg font-medium leading-8 text-foreground/80">{service.description}</p></div>
              </div>
              <div className="mt-8 max-w-3xl space-y-4 border-t border-border pt-7">{item.paragraphs.map((paragraph) => <p key={paragraph.slice(0, 48)} className="text-pretty leading-7 text-muted-foreground">{paragraph}</p>)}</div>
            </div>

            <div className="mt-10">
              <h4 className="font-display text-lg font-semibold">{english ? 'What We Deliver' : 'Neler Sunuyoruz?'}</h4>
              <ul className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{featureNames.map((feature) => <li key={feature} className="flex min-w-0 items-center gap-3 rounded-xl border border-border/80 bg-background/80 px-4 py-3 text-sm font-medium shadow-sm"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-accent/10 text-accent"><Check className="h-3.5 w-3.5" aria-hidden="true" /></span><span>{feature}</span></li>)}</ul>
            </div>

            {(highlight || benefits.length > 0) && <div className="mt-8 rounded-2xl border border-accent/15 bg-accent/[0.055] p-5 sm:p-6">
              {highlight && <p className="max-w-4xl text-balance font-display text-xl font-bold text-foreground sm:text-2xl">{highlight}</p>}
              {benefits.length > 0 && <><h4 className={`${highlight ? 'mt-5' : ''} text-sm font-semibold uppercase tracking-wider text-muted-foreground`}>{english ? 'Value for Your Business' : 'İşletmenize Ne Kazandırır?'}</h4><ul className="mt-3 flex flex-wrap gap-2">{benefits.map((benefit) => <li key={benefit} className="rounded-full border border-border bg-background px-3 py-1.5 text-sm text-foreground/80">{benefit}</li>)}</ul></>}
            </div>}

            <Link href={`${prefix}/${service.slug}`} className="group mt-9 inline-flex items-center gap-2 font-semibold text-accent transition-colors hover:text-accent/80">{item.anchor}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" aria-hidden="true" /></Link>
          </article>
        })}
      </div>

      <section className="mt-20 overflow-hidden rounded-3xl border border-border bg-primary px-5 py-10 text-primary-foreground sm:px-8 md:mt-28 md:px-12 md:py-16">
        <p className="text-sm font-semibold uppercase tracking-widest text-accent">{english ? 'Delivery Model' : 'Çalışma Süreci'}</p>
        <h3 className="mt-3 max-w-2xl font-display text-3xl font-bold sm:text-4xl">{english ? 'How We Bring a Software Project to Life' : 'Bir Yazılım Projesini Nasıl Hayata Geçiriyoruz?'}</h3>
        <ol className="relative mt-10 ml-3 border-l border-accent/40 sm:ml-4">{processes.map((step,index) => <li key={step} className="relative pb-9 pl-8 last:pb-0 sm:pl-12"><span className="absolute -left-[17px] top-0 flex h-8 w-8 items-center justify-center rounded-full border border-accent/50 bg-primary text-xs font-bold text-accent">{String(index + 1).padStart(2,'0')}</span><h4 className="font-display text-lg font-semibold">{step}</h4><p className="mt-2 max-w-2xl text-sm leading-6 text-primary-foreground/70">{english ? 'We define decisions, responsibilities and measurable review points for this stage before moving forward.' : 'Bu aşamanın kararlarını, sorumlularını ve ölçülebilir kontrol noktalarını şeffaf biçimde belirleriz.'}</p></li>)}</ol>
      </section>

      <section className="mt-16 md:mt-24"><h3 className="font-display text-2xl font-bold sm:text-3xl">{english ? 'Who Are Pars Medya Software Solutions For?' : 'Pars Medya Yazılım Çözümleri Kimler İçin Uygun?'}</h3><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">{english ? 'Our approach can support SMEs, enterprise organizations, startups, e-commerce businesses and teams in manufacturing, logistics, services, foreign trade, field operations and professional services. Suitability depends on the workflow and objective—not an unverified claim of sector experience.' : 'Yaklaşımımız KOBİ’ler, kurumsal şirketler, girişimler, e-ticaret işletmeleri ile üretim, lojistik, hizmet, dış ticaret, saha operasyonları ve profesyonel hizmet ekiplerinin farklı ihtiyaçlarına uyarlanabilir. Uygunluğu doğrulanmamış sektör referanslarıyla değil, gerçek süreç ve hedef analiziyle değerlendiririz.'}</p><ul className="mt-7 flex flex-wrap gap-3">{industries.map((industry) => <li key={industry} className="rounded-full border border-border bg-secondary/40 px-4 py-2 text-sm font-semibold">{industry}</li>)}</ul></section>

      <section className="relative mt-16 overflow-hidden rounded-3xl bg-gradient-to-br from-primary via-primary to-primary/90 p-7 text-primary-foreground sm:p-10 md:mt-24 md:p-14"><Globe2 className="h-8 w-8 text-accent" aria-hidden="true" /><h3 className="mt-5 max-w-2xl font-display text-3xl font-bold sm:text-4xl">{english ? 'From Türkiye to Global Digital Projects' : 'Türkiye’den Global Dijital Projelere'}</h3><p className="mt-5 max-w-3xl leading-7 text-primary-foreground/75">{english ? 'Our Istanbul-based perspective is enriched by business connections and project experience linked to Dubai, Moscow and Switzerland. We design multilingual, scalable products that can adapt to different markets without making unverified physical-office claims.' : 'İstanbul merkezli bakış açımızı Dubai, Moskova ve İsviçre bağlantılı iş ağları ve proje deneyimleriyle zenginleştiriyoruz. Fiziksel ofis iddiası oluşturmadan, farklı pazarların diline ve operasyon ihtiyacına uyarlanabilen çok dilli ve ölçeklenebilir yazılımlar geliştiriyoruz.'}</p><ul className="mt-8 grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-4">{['İstanbul', 'Dubai', 'Moskova', english ? 'Switzerland' : 'İsviçre'].map((location) => <li key={location} className="bg-primary/80 px-4 py-5 text-center font-display text-lg font-semibold">{location}</li>)}</ul></section>
    </div>
  </section>
}
