import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, CheckCircle2, Mail, Phone, ShieldCheck } from 'lucide-react'
import { englishServices } from '@/lib/services-en'
import { buttonVariants } from '@/components/ui/button'

export function EnglishHero() {
  return <section className="relative overflow-hidden border-b border-border"><div className="mx-auto grid max-w-6xl items-center gap-12 px-4 py-14 sm:px-6 md:py-24 lg:grid-cols-2"><div><div className="inline-flex items-center gap-2 rounded-full border border-border bg-secondary px-3 py-1 text-xs font-medium"><ShieldCheck className="h-3.5 w-3.5 text-accent" />Your trusted digital technology partner</div><h1 className="mt-6 text-balance font-display text-4xl font-bold leading-tight tracking-tight sm:text-5xl">Software and digital experiences that <span className="text-accent">move your business forward</span></h1><p className="mt-5 max-w-xl text-pretty leading-relaxed text-muted-foreground sm:text-lg">Pars Medya helps organizations grow through custom software, enterprise platforms, high-performing websites and measurable digital strategy—delivered by one accountable team.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/en/contact" className={buttonVariants({ size: 'lg' })}>Get a Free Proposal<ArrowRight className="h-4 w-4" /></Link><Link href="/en/services" className={buttonVariants({ size: 'lg', variant: 'outline' })}>Explore Services</Link></div><dl className="mt-12 grid grid-cols-3 gap-4 border-t border-border pt-8 sm:gap-6">{[['120+','Projects Delivered'],['8 Years','Industry Experience'],['98%','Client Satisfaction']].map(([value,label]) => <div key={label}><dt className="sr-only">{label}</dt><dd className="font-display text-xl font-bold sm:text-3xl">{value}</dd><p className="mt-1 text-xs text-muted-foreground sm:text-sm">{label}</p></div>)}</dl></div><div className="relative"><div className="absolute -inset-4 rounded-3xl bg-secondary/60" /><div className="relative overflow-hidden rounded-2xl border border-border shadow-xl"><Image src="/parsmedya-hero.png" alt="Digital products and software solutions developed by Pars Medya" width={720} height={560} priority quality={82} sizes="(min-width: 1024px) 560px, calc(100vw - 2rem)" className="h-auto w-full" /></div></div></div></section>
}

export function EnglishServices({ all = false }: { all?: boolean }) {
  const items = all ? englishServices : englishServices.filter((service) => service.featuredOnHome)
  return <section className="border-b border-border bg-background"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 md:py-24"><p className="text-sm font-semibold uppercase tracking-widest text-accent">Our Services</p><h2 className="mt-3 max-w-3xl text-balance font-display text-3xl font-bold sm:text-4xl">Technology solutions designed for sustainable growth</h2><p className="mt-5 max-w-4xl leading-relaxed text-muted-foreground">From strategy and product design to software engineering, integrations and digital growth, we plan every engagement around your organization’s goals.</p><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{items.map((service) => <article key={service.slug} className="group flex flex-col rounded-xl border border-border bg-card p-6 transition hover:-translate-y-1 hover:border-accent/60 hover:shadow-lg"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-secondary text-primary"><service.icon className="h-5 w-5" /></div><h3 className="mt-5 font-display text-lg font-semibold"><Link href={`/en/services/${service.slug}`} className="hover:text-accent">{service.title}</Link></h3><p className="mt-2 flex-1 text-sm leading-relaxed text-muted-foreground">{service.description}</p><Link href={`/en/services/${service.slug}`} className="mt-5 inline-flex items-center gap-1.5 text-sm font-semibold text-accent">Learn More<ArrowRight className="h-4 w-4" /></Link></article>)}</div>{!all && <div className="mt-12 flex justify-center"><Link href="/en/services" className={buttonVariants({ size: 'lg' })}>Explore All Services<ArrowRight className="h-4 w-4" /></Link></div>}</div></section>
}

export function EnglishWhyUs() {
  const reasons = [['Transparent Delivery','Clear decisions, review points and regular communication throughout the project.'],['Security by Design','Access, validation and data protection are considered from the first architecture decisions.'],['International Perspective','Project experience and business relationships across Istanbul, Dubai, Moscow and Switzerland.'],['Long-Term Partnership','Maintenance, measurement and further development continue after launch.']]
  return <section className="border-b border-border bg-secondary/40"><div className="mx-auto grid max-w-6xl gap-12 px-4 py-16 sm:px-6 md:py-24 lg:grid-cols-2"><div><p className="text-sm font-semibold uppercase tracking-widest text-accent">Why Pars Medya?</p><h2 className="mt-3 text-balance font-display text-3xl font-bold sm:text-4xl">A technology partner that understands the business behind the brief</h2><p className="mt-4 leading-relaxed text-muted-foreground">We combine commercial understanding, product thinking and engineering discipline to create solutions that remain useful, maintainable and measurable.</p></div><div className="grid gap-5 sm:grid-cols-2">{reasons.map(([title,description]) => <article key={title} className="rounded-xl border border-border bg-card p-5"><CheckCircle2 className="h-6 w-6 text-accent" /><h3 className="mt-4 font-display font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{description}</p></article>)}</div></div></section>
}

export function EnglishContactCta() {
  return <section className="bg-primary text-primary-foreground"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-4 py-16 sm:px-6 md:flex-row md:items-center md:justify-between"><div className="max-w-xl"><h2 className="font-display text-3xl font-bold sm:text-4xl">Let’s turn your next idea into a reliable digital product</h2><p className="mt-4 leading-relaxed text-primary-foreground/80">Tell us about your goals. We will review the opportunity and return with a practical next step.</p><div className="mt-6 flex flex-col gap-3 text-sm sm:flex-row sm:gap-8"><a href="mailto:info@parsmedya.net" className="inline-flex items-center gap-2"><Mail className="h-4 w-4" />info@parsmedya.net</a><a href="tel:+902129637777" className="inline-flex items-center gap-2"><Phone className="h-4 w-4" />+90 212 963 77 77</a></div></div><Link href="/en/contact" className={buttonVariants({ size: 'lg', className: 'bg-accent text-accent-foreground hover:bg-accent/90' })}>Start a Conversation<ArrowRight className="h-4 w-4" /></Link></div></section>
}
