import { services, type Service } from '@/lib/services'
import { toEnglishServiceSlug } from '@/lib/i18n'

type EnglishSeed = { title: string; description: string; hero: string; features: string[]; seoTitle: string; seoDescription: string }

const seeds: Record<string, EnglishSeed> = {
  'web-sitesi-gelistirme': { title: 'Website Development', description: 'Fast, accessible and SEO-ready corporate websites built around your brand.', hero: 'A high-performing digital home for your brand', features: ['Corporate websites','Content management','Responsive interfaces','Technical SEO','Performance optimization','Analytics integration'], seoTitle: 'Corporate Website Development | Pars Medya', seoDescription: 'Build a fast, accessible and SEO-ready corporate website that represents your brand and supports measurable growth.' },
  'mobil-uygulama': { title: 'Mobile Apps', description: 'User-focused iOS and Android applications with reliable native performance.', hero: 'Put a seamless brand experience in your customers’ hands', features: ['iOS and Android','Product design','Push notifications','API integration','Store publishing','Product support'], seoTitle: 'Mobile App Development | Pars Medya', seoDescription: 'Launch user-focused iOS and Android applications with reliable performance, integrations and long-term product support.' },
  'e-ticaret-cozumleri': { title: 'E-Commerce Solutions', description: 'Secure, scalable online sales experiences connected to your operations.', hero: 'Turn digital demand into sustainable revenue', features: ['Product catalogues','Secure checkout','Order operations','Campaigns','Shipping integrations','Sales analytics'], seoTitle: 'E-Commerce Solutions | Pars Medya', seoDescription: 'Create secure and scalable e-commerce experiences connected to your products, payments, shipping and sales operations.' },
  'seo-dijital-pazarlama': { title: 'SEO & Digital Marketing', description: 'Data-informed visibility, acquisition and conversion strategies.', hero: 'Grow visibility with measurable digital strategy', features: ['Technical SEO','Content strategy','Paid media','Conversion tracking','Campaign optimization','Performance reporting'], seoTitle: 'SEO & Digital Marketing Services | Pars Medya', seoDescription: 'Improve qualified visibility and acquisition with technical SEO, content, paid media and transparent performance reporting.' },
  'ui-ux-tasarim': { title: 'UI/UX Design', description: 'Clear, accessible and conversion-focused digital product experiences.', hero: 'Design experiences people understand and enjoy', features: ['User research','Information architecture','Wireframes','Design systems','Interactive prototypes','Usability testing'], seoTitle: 'UI/UX Design Services | Pars Medya', seoDescription: 'Design clear, accessible and conversion-focused websites and digital products grounded in real user needs.' },
  'yazilim-danismanligi': { title: 'Software Consulting', description: 'Practical technical direction for architecture, cloud and delivery decisions.', hero: 'Make confident technology decisions', features: ['Technical audits','Architecture planning','Cloud strategy','Security review','Delivery processes','Engineering support'], seoTitle: 'Software Consulting Services | Pars Medya', seoDescription: 'Make confident architecture, cloud, security and delivery decisions with practical software consulting.' },
  'web-yazilim-gelistirme': { title: 'Web Software Development', description: 'Secure multi-user web applications designed around your operations.', hero: 'Transform business processes into powerful web applications', features: ['Management panels','Customer portals','Dealer systems','Reservation systems','Order management','Role-based access','API integrations','Responsive applications'], seoTitle: 'Web Software Development | Enterprise Web Apps | Pars Medya', seoDescription: 'Build secure and scalable management panels, portals, reservation, order and workflow applications around your operations.' },
  'ozel-yazilim-gelistirme': { title: 'Custom Software Development', description: 'Purpose-built software for workflows that standard products cannot support.', hero: 'Software designed around the way your business works', features: ['Custom workflows','Industry applications','Operations management','Internal tools','Multi-user systems','Dashboards','Integrations','Automation'], seoTitle: 'Custom Software Development | Pars Medya', seoDescription: 'Replace operational workarounds with secure, integrated and scalable custom software built for your organization.' },
  'crm-yazilim-cozumleri': { title: 'CRM Software Solutions', description: 'Centralize customer records, leads, opportunities, proposals and sales activity.', hero: 'Manage customer relationships and sales from one platform', features: ['Customer and company records','Lead management','Sales pipeline','Proposals and orders','Tasks and reminders','Interaction history','Sales reporting','Email and APIs'], seoTitle: 'CRM Software Solutions | Custom CRM Development | Pars Medya', seoDescription: 'Manage customer relationships, sales pipelines, proposals and business processes with custom CRM software developed around your organization.' },
  'erp-yazilim-cozumleri': { title: 'ERP Software Solutions', description: 'Connect sales, purchasing, stock, warehouse and operations through shared data.', hero: 'Bring departments together around one reliable system', features: ['Sales and orders','Purchasing','Inventory and warehouse','Accounts and suppliers','Production','Operations','Branches and permissions','Financial integrations'], seoTitle: 'ERP Software Solutions | Custom ERP Development | Pars Medya', seoDescription: 'Manage sales, purchasing, inventory, warehouse and operations centrally with ERP software developed around your business.' },
  'e-ticaret-yazilimi': { title: 'E-Commerce Development', description: 'Custom commerce platforms for complex pricing, orders and integrations.', hero: 'An e-commerce platform shaped around your sales model', features: ['Products and variants','Pricing and campaigns','Payments','Stock and orders','Shipping','Marketplace integrations'], seoTitle: 'Custom E-Commerce Development | Pars Medya', seoDescription: 'Build a high-performance commerce platform for your product, pricing, stock, payment, shipping and marketplace workflows.' },
  'kurumsal-web-uygulamalari': { title: 'Enterprise Web Applications', description: 'Secure browser-based tools for teams, managers and business partners.', hero: 'Give teams secure access to critical workflows', features: ['Intranet tools','Request management','Document workflows','Self-service screens','Role permissions','Audit trails'], seoTitle: 'Enterprise Web Application Development | Pars Medya', seoDescription: 'Build secure enterprise web applications for internal workflows, requests, documents, teams and business partners.' },
  'mobil-uygulama-gelistirme': { title: 'Mobile App Development', description: 'End-to-end mobile products connected to your services and business systems.', hero: 'Turn your service into an intuitive mobile product', features: ['Product strategy','iOS and Android','Secure authentication','Offline workflows','Push notifications','Backend integrations'], seoTitle: 'Mobile App Development Company | Pars Medya', seoDescription: 'Develop secure, intuitive iOS and Android products connected to your services, data and business systems.' },
  'api-sistem-entegrasyonlari': { title: 'API & System Integrations', description: 'Automate reliable data flow between your existing platforms and providers.', hero: 'Connect systems and automate the flow of data', features: ['Payment systems','ERP and CRM','Accounting','SMS and email','Shipping and marketplaces','Banking and maps'], seoTitle: 'API & System Integrations | Pars Medya', seoDescription: 'Create secure automated data flows between ERP, CRM, accounting, payments, shipping, marketplaces and third-party APIs.' },
  'is-surecleri-otomasyonu': { title: 'Business Process Automation', description: 'Reduce repetitive work with controlled approvals, tasks and data flows.', hero: 'Give your team more time for valuable work', features: ['Approval workflows','Task assignment','Notifications','Document generation','Data transfer','Exception management'], seoTitle: 'Business Process Automation | Pars Medya', seoDescription: 'Automate approvals, tasks, notifications, documents and system-to-system data flows while retaining the right controls.' },
  'b2b-b2c-platform-gelistirme': { title: 'B2B & B2C Platform Development', description: 'Platforms connecting customers, dealers, suppliers and end users.', hero: 'Bring your business ecosystem onto one scalable platform', features: ['User segments','Custom catalogues','Pricing rules','Orders and requests','Commissions','Payments and integrations'], seoTitle: 'B2B & B2C Platform Development | Pars Medya', seoDescription: 'Connect dealers, suppliers, customers and consumers through a secure, integrated and scalable digital platform.' },
  'saas-yazilim-gelistirme': { title: 'SaaS Development', description: 'Scalable subscription products with tenant, plan and usage management.', hero: 'Turn your idea into a scalable SaaS product', features: ['Multi-tenant architecture','Subscriptions and plans','Payment integration','Users and roles','Usage limits','Dashboards and notifications'], seoTitle: 'SaaS Development | Multi-Tenant Products | Pars Medya', seoDescription: 'Build a scalable SaaS product with multi-tenant architecture, subscriptions, payments, roles, plans and usage controls.' },
  'dashboard-raporlama-sistemleri': { title: 'Dashboard & Reporting Systems', description: 'Turn data from multiple sources into useful KPIs and management views.', hero: 'Make operational data clear and actionable', features: ['KPI cards','Charts and tables','Filters and segments','Role-based reports','Exports','Data integrations'], seoTitle: 'Dashboard & Reporting Systems | Pars Medya', seoDescription: 'Transform ERP, CRM and operational data into role-based dashboards, KPIs and decision-ready management reports.' },
  'musteri-bayi-portali': { title: 'Customer & Dealer Portals', description: 'Secure self-service access to orders, pricing, requests and documents.', hero: 'Offer customers and dealers a seamless self-service experience', features: ['Accounts and roles','Custom pricing','Orders','Support requests','Documents','ERP and CRM integration'], seoTitle: 'Customer & Dealer Portal Development | Pars Medya', seoDescription: 'Give customers and dealers secure self-service access to orders, pricing, support requests, documents and account information.' },
  'stok-siparis-yonetim-sistemleri': { title: 'Inventory & Order Management', description: 'Track multi-warehouse inventory, orders, reservations and fulfilment.', hero: 'Control inventory and order flow from end to end', features: ['Multiple warehouses','Stock movements','Order workflows','Stock counts','Reorder alerts','Returns'], seoTitle: 'Inventory & Order Management Systems | Pars Medya', seoDescription: 'Manage multi-warehouse inventory, reservations, stock movements, orders, fulfilment, counts and returns in one system.' },
  'yapay-zeka-destekli-yazilim': { title: 'AI-Powered Software Solutions', description: 'Apply AI responsibly to documents, search, support and content workflows.', hero: 'Apply AI to real business processes with control', features: ['Document analysis','Classification','Customer-service assistants','Summarization','Intelligent search','Workflow support'], seoTitle: 'AI-Powered Software Solutions | Pars Medya', seoDescription: 'Apply AI responsibly to document analysis, classification, support, summarization, intelligent search and internal knowledge workflows.' },
  'yazilim-modernizasyonu': { title: 'Software Modernization', description: 'Upgrade legacy systems through controlled, business-safe modernization.', hero: 'Reduce technical debt while protecting business continuity', features: ['Technical audit','Architecture modernization','Interface renewal','Data migration','Cloud readiness','Automated testing'], seoTitle: 'Legacy Software Modernization | Pars Medya', seoDescription: 'Modernize slow or difficult legacy applications through controlled architecture, interface, data and cloud improvements.' },
}

export type EnglishService = Service & { trSlug: string }
const process = ['Discovery and needs analysis','Business process analysis','Technical architecture','UI/UX design','Iterative development','Testing and security','Controlled launch','Continuous support']

export const englishServices: EnglishService[] = services.map((service) => {
  const seed = seeds[service.slug]
  return { ...service, trSlug: service.slug, slug: toEnglishServiceSlug(service.slug), title: seed.title, description: seed.description, tagline: seed.hero, intro: seed.description, longDescription: [seed.description, `We examine users, roles, data and integrations before defining a maintainable solution. The result is designed for everyday operations rather than a generic feature checklist.`, `Security, performance, accessibility and scalability are considered from the beginning so the product can evolve safely as your organization grows.`], features: seed.features.map((title) => ({ title, description: `${title} is designed around your users, operational rules and measurable business objectives.` })), benefits: ['Reduce manual work and avoidable errors','Create one reliable source of operational data','Improve visibility and accountability','Support secure role-based collaboration','Scale with new users, locations and integrations'], useCases: [{ title: 'Growing organizations', description: 'Teams replacing spreadsheets and disconnected tools with managed workflows.' }, { title: 'Multi-team operations', description: 'Processes requiring shared data, approvals and clear responsibilities.' }, { title: 'Digital products', description: 'Customer-facing services that need secure and scalable technology.' }], process: process.map((title) => ({ title, description: `We complete the ${title.toLowerCase()} stage transparently with clear decisions and review points.` })), whyParsMedya: 'Pars Medya combines business analysis, product design and software engineering in one accountable team. We communicate clearly, avoid unnecessary complexity and build maintainable systems that can grow with your organization and international ambitions.', faqs: [{ question: `How long does a ${seed.title.toLowerCase()} project take?`, answer: 'Timing depends on scope, roles, integrations and migration needs. After discovery we provide a realistic phased plan.' }, { question: 'Can the solution integrate with our existing systems?', answer: 'Yes. We assess available APIs and secure data-transfer options before defining the integration approach.' }, { question: 'Do you provide support after launch?', answer: 'Yes. Monitoring, maintenance and further development can continue under an agreed support model.' }, { question: 'How do you approach security?', answer: 'We apply least-privilege access, validation, auditability and secure delivery practices according to the project’s risk profile.' }], seoTitle: seed.seoTitle, seoDescription: seed.seoDescription }
})

export const getEnglishService = (slug: string) => englishServices.find((service) => service.slug === slug)
