import type { Metadata } from 'next'
import { CorporateDetail } from '@/components/corporate-detail'
import { localizedAlternates } from '@/lib/seo'

export const metadata: Metadata = { title: 'Our Vision | Pars Medya', description: 'Explore Pars Medya’s long-term vision for software, digital transformation and internationally competitive technology solutions.', alternates: localizedAlternates('/en/vision', '/vizyonumuz', '/en/vision') }
const paragraphs = [
  'Our vision is to grow from Türkiye into an internationally trusted technology brand that brings business strategy, product design and software engineering together. We aim to build digital foundations that address immediate priorities while remaining adaptable to changing markets, operating models and customer expectations.',
  'Across web applications, custom software, CRM, ERP and SaaS products, we begin with the understanding that every organization works differently. Scalable architecture, secure data flows and maintainable engineering allow each platform to grow with new users, processes, markets and integrations.',
  'We approach AI-powered systems as responsible business tools rather than technology for its own sake. Applied thoughtfully, artificial intelligence can improve access to knowledge, reduce repetitive work and support better decisions while preserving human oversight, data protection and operational control.',
  'Digital transformation succeeds when technology, people and processes evolve together. We therefore study real user needs, simplify complex workflows and create accessible experiences that teams can adopt with confidence. User experience is not a finishing layer; it shapes every product decision.',
  'We seek long-term customer relationships grounded in honest communication and shared learning. Our idea of a reliable technology partnership includes realistic planning, visible progress, clear responsibilities and continuous improvement long after the first release.',
  'Innovation and sustainable growth must reinforce one another. By combining local understanding with international project experience, we aim to create solutions that help organizations compete across markets without sacrificing maintainability, security or clarity.',
]
const principles = [
  { title: 'Innovation', description: 'We connect emerging technology with practical challenges and measurable business value.' }, { title: 'Global Perspective', description: 'We design products for different markets, user expectations and operating environments.' }, { title: 'Reliability', description: 'Transparent communication, secure delivery and accountable decisions guide every engagement.' }, { title: 'Scalable Technology', description: 'Our architectures grow predictably with users, data, transactions and integrations.' }, { title: 'User Focus', description: 'We turn complex operations into clear, accessible and productive digital experiences.' }, { title: 'Sustainable Success', description: 'We balance near-term progress with maintainability, continuous evolution and lasting value.' },
]
export default function EnglishVisionPage() { return <CorporateDetail locale="en" title="Our Vision" description="To become an internationally trusted software and digital transformation partner, creating scalable technology that delivers lasting business value." paragraphs={paragraphs} principles={principles} globalText="Our perspective begins in Istanbul and is enriched by business relationships and project experience connected to Dubai, Moscow and Switzerland. Without implying a physical office presence, this network helps us understand different markets and deliver digital solutions through shared quality standards, strong communication and local awareness." ctaTitle="Let’s shape your digital future together." /> }
