'use client'

import { useState } from 'react'
import { savePost } from '@/app/admin/actions'
import type { BlogPost } from '@/lib/supabase/types'

const slugify = (value: string) => value.toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/ı/g, 'i').replace(/ğ/g, 'g').replace(/ü/g, 'u').replace(/ş/g, 's').replace(/ö/g, 'o').replace(/ç/g, 'c').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
const input = 'mt-1.5 w-full rounded-lg border border-input bg-background px-3 py-2.5 text-sm outline-none focus:border-ring focus:ring-2 focus:ring-ring/20'

export function BlogForm({ post, error }: { post?: BlogPost; error?: string }) {
  const [slug, setSlug] = useState(post?.slug || '')
  const [edited, setEdited] = useState(Boolean(post))
  return <form action={savePost} className="space-y-6"><input type="hidden" name="id" value={post?.id || ''} /><input type="hidden" name="current_image_url" value={post?.image_url || ''} />{error && <p role="alert" className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="grid gap-5 lg:grid-cols-2"><label className="text-sm font-medium">Başlık *<input required name="title" defaultValue={post?.title} className={input} onChange={(e) => { if (!edited) setSlug(slugify(e.target.value)) }} /></label><label className="text-sm font-medium">Slug *<input required name="slug" value={slug} className={input} onChange={(e) => { setEdited(true); setSlug(slugify(e.target.value)) }} /></label><label className="text-sm font-medium">Kategori *<input required name="category" defaultValue={post?.category} className={input} /></label><label className="text-sm font-medium">Yazar *<input required name="author" defaultValue={post?.author || 'Pars Medya Ekibi'} className={input} /></label></div><label className="block text-sm font-medium">Kısa açıklama *<textarea required name="excerpt" defaultValue={post?.excerpt} rows={3} className={input} /></label><label className="block text-sm font-medium">İçerik *<span className="ml-2 font-normal text-muted-foreground">Başlıklar için ## kullanabilirsiniz.</span><textarea required name="content" defaultValue={post?.content} rows={16} className={input} /></label><div className="grid gap-5 lg:grid-cols-2"><label className="text-sm font-medium">Kapak görseli<input name="image" type="file" accept="image/jpeg,image/png,image/webp,image/gif" className={input} /><span className="mt-1 block text-xs font-normal text-muted-foreground">JPG, PNG, WebP veya GIF — en fazla 5 MB</span></label><label className="text-sm font-medium">Yayın tarihi<input name="published_at" type="datetime-local" defaultValue={post?.published_at?.slice(0, 16)} className={input} /></label><label className="text-sm font-medium">SEO title<input name="seo_title" defaultValue={post?.seo_title || ''} className={input} /></label><label className="text-sm font-medium">SEO description<textarea name="seo_description" defaultValue={post?.seo_description || ''} rows={2} className={input} /></label><label className="text-sm font-medium">Durum<select name="status" defaultValue={post?.status || 'draft'} className={input}><option value="draft">Taslak</option><option value="published">Yayında</option></select></label></div><button className="rounded-lg bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground hover:bg-primary/90">{post ? 'Değişiklikleri Kaydet' : 'Yazıyı Oluştur'}</button></form>
}
